Default: &defaults
  host: "127.0.0.1"
  port: 3001
  approot: "http://localhost:3001"
  copyright: Copyright (C) 2011 Kazu Yamamoto
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://localhost/app/gitcab"
  <<: *defaults
